//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp50
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int kind_product_id { get; set; }
        public int c_or_s_id { get; set; }
        public string pack { get; set; }
        public decimal remain { get; set; }
    
        public virtual client_or_supplier client_or_supplier { get; set; }
        public virtual kind_product kind_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
