//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp50
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int kind_product_id { get; set; }
    
        public virtual kind_product kind_product { get; set; }
    }
}
