//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp50
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int Id { get; set; }
        public int shift_time_id { get; set; }
        public int shift_day_id { get; set; }
        public int date_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<int> hours_of_working { get; set; }
    
        public virtual date date { get; set; }
        public virtual employee employee { get; set; }
        public virtual shift_day shift_day { get; set; }
        public virtual shift_time shift_time { get; set; }
    }
}
